# Generated by Django 2.0.3 on 2018-07-06 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user_group',
        ),
        migrations.AlterField(
            model_name='clientrequest',
            name='technician',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'Technicians'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
