# Generated by Django 2.0.3 on 2018-07-02 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestentry',
            name='technician',
        ),
        migrations.DeleteModel(
            name='RequestEntry',
        ),
    ]
